### ISSUE TITLE
Unique identifier code required in darleq3_taxa

### ISSUE THREAD

**Issue by ecodata1** [nsj3/darleq3#1]
Hi Steve,

This is a great package! :smile:  :fireworks: 

I've helped write a similar packages for use internally in SEPA called [phytobenthosMetrics](https://github.com/aquaMetrics/phytobenthosMetrics). It's not as complete as this package. It's based on DARLEQ2 uktag tool. I'd like to shift away from using our internal package in SEPA so there's just a single tool/source of truth :+1: . I've only recently been aware that this darleq3 package exists.

The only issue is taxonomic changes since DARLEQ2. We only store the taxon name and abundance values as results in our database - not the associated codes. So any change in the taxon name can cause issues with matching to the codes/TDI scores. We avoided storing codes because neither the NBScode or TaxonID is unique identifier:

 ` length(darleq3_taxa$NBSCode[duplicated(darleq3_taxa$NBSCode)])  # 38 - NAs - missing codes` 
` length(darleq3_taxa$TaxonId[duplicated(darleq3_taxa$TaxonId)])  #  3`

Only the Taxon name is unique:
 `  length(darleq3_taxa$TaxonName[duplicated(darleq3_taxa$TaxonName)]) # 0`

However, the Taxon name has changed due to correction of typos etc over time between DARLEQ2 and Darleq3 so we can no longer match our taxon names to darleq3 scores/values etc.

My suggestion is that we have a column that is a unique identifier within darleq3_taxa (other than the taxonName) - maybe making TaxonID unique for all taxa? I can then add this unique ID against all the records in our database and going forward any changes to darleq3_taxa will be easy to pick up/match to records in our database?

**Comment by nsj3** [comment]
I think you can use either TaxonID or the NBSCode.  TaxonID is unique.  The 3 duplicates you identified are errors and will be fixed in the next commit.  NBSCodes are also unique.  These duplicates  are all NAs. They are taxon names from a legacy project that the EA and I guess SEPA don't use and do not have NBS codes.  Any TaxonID or NBSCode will (and should) only ever be linked to a single taxon name in the list.

**Comment by ecodata1** [comment]
Thanks, that's good to know. I'll use TaxonID. SEPA does have taxa records which don't match against NBScodes - so can't use that as a unique identifier. SEPA had legacy projects too. There was a plan for all the agencies to use a single taxa list/NBScodes etc but in the end we used the full lists from the WFD tools themselves so used DARES and then DARLEQ list (and accordingly for other WFD tools etc). We also had legacy lists and data also. I would prefer to use NBS codes but that breaks backwards compatibility/comparisons when we need to run tdi5 etc on legacy results even if generally there would only be a few minor discrepancies. 

Thanks again,
Tim

**Comment by ecodata1** [comment]
Thanks for the update to TaxonID. 
` length(darleq3_taxa$TaxonId[duplicated(darleq3_taxa$TaxonId)]) = 0`
